name: Auto-Update Top Repositories Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

# 👇 THIS IS THE FIX: Giving the action permission to save the image
permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Top Repositories & Lines of Code
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          config_timezone: Asia/Kolkata
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 5
          plugin_repositories: yes
          plugin_repositories_featured: AvanishSalunke/AvanishSalunke
          plugin_repositories_order: featured, pinned, starred, random
